---
# tasks file for create_syntropy_network
- name: Create Syntropy Network
  syntropynet.syntropy.syntropy_network:
    name: "{{network_name}}"
    state: present
    topology: p2m
    connections:
      mqt_2_broker:
        state: present
        type: endpoint
        services:
          - mosquitto
        connect_to:
          client:
            state: present
            services:
              - nodejs-publisher
              - nodejs-subscriber
            type: tag
