---
- include_vars: ../../../secrets.yaml

- name: Copy Kibana template
  copy:
    src: kibana.yaml
    dest: ~/auth/
    mode: "0644"

- name: Launch kibana
  docker_container:
    image: docker.elastic.co/kibana/kibana:7.10.2
    name: kibana
    volumes:
      - ~/auth/kibana.yaml:/usr/share/kibana/config/kibana.yml
    env:
      discovery.type: "single-node"
      VIRTUAL_HOST: "{{duck_dns_domain}}"
      VIRTUAL_PORT: "5601"
      LETSENCRYPT_HOST: "{{duck_dns_domain}}"
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
    purge_networks: yes
    networks:
      - name: "{{network_name}}"
