version: "2"
services:
  syntropynet-agent:
    image: syntropynet/agent:stable
    hostname: syntropynet-agent
    container_name: syntropynet-agent
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SYNTROPY_API_KEY=YOUR-API-KEY
      - SYNTROPY_NETWORK_API=docker
      - SYNTROPY_AGENT_NAME=AGENT-NAME
      - SYNTROPY_PROVIDER=6
      - SYNTROPY_TAGS=TAG
      - SYNTROPY_SERVICES_STATUS=false
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices:
      - "/dev/net/tun:/dev/net/tun"

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    depends_on:
      - syntropynet-agent

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24