version: "2"
services:
  syntropynet-agent:
    image: syntropynet/agent:stable
    hostname: syntropynet-agent
    container_name: syntropynet-agent
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SYNTROPY_API_KEY=YOUR-API-KEY
      - SYNTROPY_NETWORK_API=docker
      - SYNTROPY_AGENT_NAME=AGENT-NAME
      - SYNTROPY_PROVIDER=6
      - SYNTROPY_TAGS=TAG
      - SYNTROPY_SERVICES_STATUS=false
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices:
      - "/dev/net/tun:/dev/net/tun"
  mongo:
    image: 'mongo:latest'
    hostname: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=jvs_1_api
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24