---
# tasks file for launch_nodejs

- debug:
    msg: Launching NodeJS for "{{app_name}}"

# run the container
- name: Run NodeJS
  docker_container:
    name: "{{app_name}}"
    image: node12
    purge_networks: yes
    networks:
      - name: "{{network_name}}"
