---
   - name: Update package repository and install software
     apt: name={{ item }} state=present update_cache=yes
     with_items:
          - samba
          - winbind
          - libnss-winbind
          - libpam-winbind
          - python-pexpect
   - name: remove localhost
     lineinfile:
       path: /etc/hosts
       state: absent
       regexp: '^127.*$'

   - name: Generate new resolv.conf
     template:
       src: templates/resolv.conf.j2
       dest: /etc/resolv.conf
       owner: root
       group: root
       mode: '0644'
        
   - name: Create PAM winbind file
     file: path={{ item }} owner=root group=root mode=644 state=touch
     with_items:
          - /etc/security/pam_winbind.conf

   - name: Fill in hosts file
     blockinfile:
       path: /etc/hosts
       block: |
        127.0.0.1 {{ ansible_hostname }}.{{ domain | lower }} {{ ansible_hostname }} localhost

   - name: Generate Samba config
     template:
       src: templates/smb.conf.j2
       dest: /etc/samba/smb.conf
       owner: root
       group: root
       mode: '0644'

   - name: copy /etc/nsswitch.conf
     copy:
       src=files/nsswitch.conf
       dest=/etc/nsswitch.conf
       owner=0
       group=0
       mode=0644
 
   - name: AD join
     expect:
       command: net ads join -U administrator -S {{ dc_ip }}
       responses:
         (?i)password: "{{ domainpass }}"

   - name: flush net cache
     tags: winbind
     shell: /usr/bin/net cache flush

   - name: restart winbind
     service:
       name=winbind
       state=restarted

   - name: Get AD group SID
     shell: wbinfo -n "{{ allowed_group_name }}"
     register: sid

   - name: Fill in pam_winbind
     blockinfile:
       path: /etc/security/pam_winbind.conf
       block: |
        [global]
        ;debug = no
        ;debug_state = no
        cached_login = no
        ;krb5_auth = no
        ;krb5_ccache_type =
        require_membership_of = {{ sid.stdout }}
        ;warn_pwd_expire = 14
        ;silent = no


   - name: Update pamd rule's control in /etc/pam.d/common-session
     pamd:
       name: common-session
       type: session
       control: required
       module_path: pam_unix.so
       new_type: session
       new_control: required
       new_module_path: pam_mkhomedir.so umask=0022 skel=/etc/skel
       state: after

   - name: Allow password authentication
     lineinfile:
       path: /etc/ssh/sshd_config
       regex: ^PasswordAuthentication no
       line: PasswordAuthentication yes

   - name: reload sshd
     service:
       name=sshd
       state=reloaded
