---
- name: Collect IPFS Node Peer IDs
  hosts: [all]
  roles:
    - remove_bootstrap_peers
    - collect_ipfs_peer_ids

## Collect Peer IDs and store them in a file
- name: Create Peer config file
  hosts: [localhost]
  vars:
    group: "all"
  roles:
    - create_peer_config_file

##### BOOOTSTRAP NODES #########

- name: Bootstrap Gateway
  hosts: [all]
  vars:
    group: "all"
  roles:
    - bootstrap_add_peers
