---
- name: Deploy IPFS syntropy network
  hosts: [localhost]
  tasks:
    - name: Create network
      syntropynet.syntropy.syntropy_network:
        name: ipfs-mesh
        state: present
        topology: mesh
        connections:
          ipfs:
            state: present
            type: tag
