#!/usr/bin/env ansible-playbook
---
- name: Configure Broker
  hosts: digitalocean
  vars:
    syntropy_api_token: "{{ lookup('env','SYNTROPY_API_TOKEN') }}"
    mosquitto_conf: ./mosquitto.conf
    mosquitto_name: mosquitto

  tasks:
    # Create the network
    - name: Create network
      docker_network:
        name: syntropynet
        driver: bridge
        ipam_config:
          - subnet: 172.20.0.0/24

    # Run the syntropy agent
    - name: Run Syntropy Agent
      docker_container:
        image: syntropynet/agent:stable
        name: syntropynet-agent
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        env:
          SYNTROPY_API_KEY: # redacted
          SYNTROPY_NETWORK_API: "docker"
          SYNTROPY_AGENT_NAME: "mqt_2_broker"
          SYNTROPY_PROVIDER: "6" # Digital Ocean
          SYNTROPY_TAGS: "mqtt"
          SYNTROPY_SERVICES_STATUS: "false" # default is false
        restart_policy: always
        network_mode: "host"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        devices:
          - "/dev/net/tun:/dev/net/tun"

    # copy the mosquito config
    - name: Copy mosquitto conf
      copy:
        src: broker/mosquitto.conf
        dest: mosquitto.conf
        mode: "0644"

    # launch mosquitto container
    - name: Launch Mosquitto
      docker_container:
        name: "{{ mosquitto_name }}"
        image: eclipse-mosquitto
        hostname: "{{ mosquitto_name }}"
        volumes:
          - /mosquitto.conf
        networks:
          - name: syntropynet
