---
- name: "MQT2 Network"
  hosts: localhost
  collections: all

  tasks:
    # - name: Print env
    #   debug:
    #     msg: "{{ lookup('env','SYNTROPY_PASSWORD') }}"

    - name: Login
      syntropynet.syntropy.syntropy_login:
        api_url: https://controller-prod-server.syntropystack.com
        username: craigpick@gmail.com
        password: "{{ lookup('env','SYNTROPY_PASSWORD') }}"
      register: api_token

    - name: print token
      debug:
        msg: "{{ api_token.token }}"

    - name: Gather facts
      syntropynet.syntropy.syntropy_facts:
        api_url: https://controller-prod-server.syntropystack.com
        api_token: "{{ api_token.token }}"
        endpoint_tags: ["mqtt"]
        gather_subset: ["endpoints"]
      register: facts

    - name: Dump facts output
      debug:
        msg: "{{ facts.facts }}"

    - name: Retrieve topology
      syntropynet.syntropy.syntropy_facts:
        endpoint_tags: ["mqtt"]
        gather_subset: ["endpoints"]
