version: "3.7"
services:
  syntropynet-agent:
    image: syntropynet/agent:stable
    hostname: syntropynet-agent
    container_name: syntropynet-agent
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SYNTROPY_API_KEY=YOUR-API-KEY
      - SYNTROPY_NETWORK_API=docker
      - SYNTROPY_AGENT_NAME=AGENT-NAME
      - SYNTROPY_PROVIDER=6
      - SYNTROPY_TAGS=TAG
      - SYNTROPY_SERVICES_STATUS=false
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices:
      - "/dev/net/tun:/dev/net/tun"

  jvs_1_calc:
    build:
      context: ./
      target: prod
    volumes:
      - ./.env:/app/.env
    ports:
      - '8849:8849'
      
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24