- name: Remove container
  docker_container:
    name: master-0
    state: absent
    image: "bitnami/postgresql-repmgr"
- name: Delete a network
  docker_network:
    name: syntropynet
    state: absent
    force: yes

- name: Create docker network
  become: yes
  become_user: root
  docker_network:
    name: syntropynet
    ipam_config:
      - subnet: 10.48.0.0/16
- name: Install Postgres container on master
  docker_container:
    name: master-0
    image: "bitnami/postgresql-repmgr"
    state: started
    env:
     REPMGR_PARTNER_NODES: master-0,10.49.0.2,10.50.0.2
     REPMGR_NODE_NAME: master-0 
     REPMGR_NODE_NETWORK_NAME: master-0 
     REPMGR_PRIMARY_HOST: master-0 
     REPMGR_PASSWORD: repmgrpass 
     POSTGRESQL_POSTGRES_PASSWORD: adminpassword 
     POSTGRESQL_USERNAME: customuser 
     POSTGRESQL_PASSWORD: custompassword 
     POSTGRESQL_DATABASE: customdatabase 
     SYNTROPY_SERVICE_NAME: postgres
     REPMGR_NODE_ID: "1"
    network_mode: "syntropynet"
    restart: yes
    detach: yes
    restart_policy: always
  retries: 5
  delay: 30

