---
# Deploy Elastic Search
- name: Deploy Bootstrap Node
  hosts: [DigitalOcean]
  vars:
    agent_name: "cluster0_bootstrap"
    agent_tags: "cluster0"
    agent_provider: "6" # <=== replace this
    network_name: "syntropynet"
    subnet: 172.20.0.0/24
    ipfs_node_multiaddress: 172.20.0.2
    ipfs_listen_multiaddress: 172.20.0.3 # TODO: remove this
    ipfs_name: { { inventory_hostname } } # take the name from the inventory file
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_ipfs

    # Deploy Elastic Search
- name: Deploy Bootstrap Node
  hosts: [GCP]
  vars:
    agent_name: "cluster1_bootstrap"
    agent_tags: "cluster1"
    agent_provider: "3" # <=== replace this
    network_name: "syntropynet"
    subnet: 172.21.0.0/24
    ipfs_node_multiaddress: 172.21.0.2
    ipfs_listen_multiaddress: 172.21.0.3
    ipfs_name: { { inventory_hostname } } # take the name from the inventory file
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_ipfs

- name: Deploy Bootstrap Node
  hosts: [AWS]
  vars:
    agent_name: "cluster2_bootstrap"
    agent_tags: "cluster2"
    agent_provider: "1" # <=== replace this
    network_name: "syntropynet"
    subnet: 172.22.0.0/24
    ipfs_node_multiaddress: 172.22.0.2
    ipfs_listen_multiaddress: 172.22.0.3
    ipfs_name: { { inventory_hostname } } # take the name from the inventory file
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_ipfs
