---
- name: Teardown containers
  hosts: all

  tasks:
    # Stop thee running containers
    - name: Get a list of all running containers
      docker_host_info:
        containers: True
      register: docker_info
    - name: Stop all running containers
      docker_container:
        name: '{{ item.Names[0] | regex_replace("^/", "") }}'
        state: stopped
      loop: "{{ docker_info.containers }}"

    # Prune it all!
    - name: Prune everything (including non-dangling images)
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes

    - name: remove data directory
      become: yes
      become_user: root
      command: rm -rf ~/data

    - name: get the username running the deploy
      become: false
      command: whoami
      register: host_username

    - name: rm with file
      become: yes
      become_user: root
      ansible.builtin.file:
        path: ~/data
        state: directory
        recurse: yes
        owner: "{{host_username.stdout}}"
        group: "{{host_username.stdout}}"
