---
# Deploy the broker
- name: Deploy Broker
  hosts: broker
  vars:
    subnet: 172.20.0.0/24
    agent_name: "mqt_3_broker"
    agent_tags: "mqtt"
    agent_provider: "6"
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - launch_mosquitto

# Deploy the Publisher
- name: Deploy Publisher
  hosts: publisher
  vars:
    subnet: 172.21.0.0/24
    agent_name: "mqt_3_publisher"
    agent_tags: "mqtt"
    agent_provider: "3"
    app_src: "publisher"
    app_name: "nodejs-publisher"
    network_name: "syntropynet"
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - create_app_image
    - launch_nodejs

# Deploy the Subscriber
- name: Deploy Subscriber
  hosts: subscriber
  vars:
    subnet: 172.22.0.0/24
    agent_name: "mqt_3_subscriber"
    agent_tags: "mqtt"
    agent_provider: "1"
    app_src: "subscriber"
    app_name: "nodejs-subscriber"
    network_name: "syntropynet"
  roles:
    - create_docker_network
    - launch_syntropy_agent
    - create_app_image
    - launch_nodejs
