
- name: Install Pgpool repo
  yum:
    name: https://www.pgpool.net/yum/rpms/4.1/redhat/rhel-7-x86_64/pgpool-II-release-4.1-2.noarch.rpm
    state: present

- name: Install Pgpool
  yum:
    name: pgpool-II-pg12
    state: present
