---
- name: Install Pgpool repo
  yum:
    name: https://www.pgpool.net/yum/rpms/4.1/redhat/rhel-7-x86_64/pgpool-II-release-4.1-2.noarch.rpm
    state: present

- name: Install Pgpool
  yum:
    name: pgpool-II-pg12
    state: present

- name: Set Pgpool configuration file
  template: src=templates/pgpool.j2 dest=/etc/pgpool2/pgpool.conf

- name: Remove local trust login entry
  lineinfile:
    dest: /etc/pgpool2/pool_hba.conf
    regexp: "^local   all"
    state: absent

- name: Allow backend db login from pgpool
    lineinfile:
      dest: /etc/pgpool2/pool_hba.conf
      line: "local all all md5"
      # regexp: "^#local all"

- name: generate password for postgres login
  shell: pg_md5 -u {{pool_user}} -m {{pool_user_password}}

- name: Install failover script to path
  template: 
    src: templates/failover.sh.j2 
    dest: /usr/bin/failover.sh
    mode: 0755

- name: Check for the postgres service
  service: 
    name: pgpool2
    state: started
