#- name: Create docker network
#  become: true
#  become_user: root
 # docker_network:
   # name: syntropynet
   # ipam_config:
    #  - subnet: 10.44.0.0/16
- name: Install Pgpool  container
  docker_container:
    name: pgpool
    image: bitnami/pgpool
    state: started
   # network_mode:
     # - name: syntropynet
    restart: yes
    restart_policy: always
  register: result
  until: result is success
  retries: 5
  delay: 30
