---
- name: Launch ElasticSearch
  docker_container:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    name: "{{service_name}}"
    env:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # <==== sets the heap size
      discovery.type: "single-node"
      node.store.allow_mmap: "false"
    purge_networks: yes
    networks:
      - name: "{{network_name}}"
